export * from './Home'
export * from './quienes-somos/Historia'
export * from './quienes-somos/EmblemaInstitucional'
export * from './quienes-somos/MisionVision'
export * from './catalogo-bomberil/UniformeInstitucional'
export * from './documentos/Estatutos'
export * from './documentos/Reglamentos'
export * from './documentos/ManualCovid'
export * from './fundacion-de-capacitacion/Cursos'
export * from './fundacion-de-capacitacion/Talleres'
export * from './fundacion-de-capacitacion/Capacitaciones'
export * from './bomberos/Aniversarios'
export * from './bomberos/CuerpoDeBomberos'
export * from './bomberos/QuieresSerBombero'
export * from './bomberos/ProfesionalesDeLaEmergencia'
export { Historia as HistoriaBomberos } from './bomberos/Historia'
